= Camel Insecure HTTP Component

A Spring/OSGi(non-cdi) based insecure custom HTTPS4 component implementation inspired by
https://pgaemers.wordpress.com/2017/02/17/creating-an-insecure-http4-component-in-apache-camel/[Creating Insecure Http4 Component]


== Install

Clone the project to your local directory and just run `./mvnw -DskipTests clean install`

== Usage

To make use of the camel component add the following dependency to your maven project,

[source,xml]
----
 <dependency>
     <groupId>org.workspace7.camel.component</groupId>
     <artifactId>camel-insecurehttps4</artifactId>
     <version>1.0-SNAPSHOT</version>
 </dependency>
----

This component is an extension of http://camel.apache.org/http4.html[Camel HTTP4] component, hence all the properties and
options of HTTP4 are valid with this component as well. To use this component in your route, use uri name as `insecurehttps4`
instead of standard `https4`

e.g.

[source,java]
----
 from("timer://calculator?fixedRate=true&period=10s")
 .to("insecurehttps4://localhost:8443/api/calculator/sub/1/2") //<1>
 .log("${body}");
----

<1> with a typical `https4` component this uri would look like `https4://localhost:8443/api/calculator/sub/1/2`

== License

Copyright 2017 Kamesh Sampath<kamesh.sampath@hotmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.